/*
 * Copyright (C) 2021 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef OHOS_RIL_REQUEST_H
#define OHOS_RIL_REQUEST_H

#define HRIL_RESPONSE_ACKNOWLEDGEMENT 800
typedef enum {
    HREQ_CALL_BASE = 0,
    HREQ_CALL_GET_CALL_LIST,
    HREQ_CALL_DIAL,
    HREQ_CALL_HANGUP,
    HREQ_CALL_REJECT,
    HREQ_CALL_ANSWER,
    HREQ_CALL_HOLD, // call hold value 6
    HREQ_CALL_ACTIVE, // call active value 6
    HREQ_CALL_SWAP,
    HREQ_CALL_JOIN,
    HREQ_CALL_SPLIT, // Keep all other calls except the xth call
    HREQ_CALL_SUPPLEMENT,
    HREQ_CALL_SEND_DTMF,
    HREQ_CALL_START_DTMF,
    HREQ_CALL_STOP_DTMF,
    HREQ_CALL_SET_CLIP,
    HREQ_CALL_DEAL_CLIP,
    HREQ_CALL_GET_CALL_WAIT,
    HREQ_CALL_SET_CALL_WAIT,
    HREQ_CALL_GET_CALLER_ID,
    HREQ_CALL_SET_CALLER_ID,
    HREQ_CALL_GET_CALL_RESTRICTION,
    HREQ_CALL_SET_CALL_RESTRICTION,
    HREQ_CALL_GET_CALL_FORWARDING,
    HREQ_CALL_SET_CALL_FORWARDING,
    HREQ_CALL_DEAL_CLIR,
    HREQ_CALL_SET_CLIR,

    HREQ_SMS_BASE = 100,
    HREQ_SMS_SEND_SMS,
    HREQ_SMS_STORAGE_SMS,
    HREQ_SMS_DELETE_SMS,
    HREQ_SMS_UPDATE_SMS,
    HREQ_SMS_SEND_SMS_MORE_MODE,
    HREQ_SMS_SEND_SMS_ACK,
    HREQ_SMS_IMS_SEND_SMS,
    HREQ_SMS_SET_CENTER_ADDRESS,
    HREQ_SMS_GET_CENTER_ADDRESS,
    HREQ_SMS_SET_CELL_BROADCAST,

    HREQ_SIM_BASE = 200,
    HREQ_SIM_GET_SIM_STATUS,
    HREQ_SIM_GET_IMSI,
    HREQ_SIM_IO,
    HREQ_SIM_GET_ICCID,
    HREQ_SIM_GET_LOCK_STATUS,
    HREQ_SIM_SET_LOCK,
    HREQ_SIM_CHANGE_PASSWD,
    HREQ_SIM_ENTER_PIN,
    HREQ_SIM_UNLOCK_PIN,
    HREQ_SIM_GET_PIN_INPUT_TIMES,

    HREQ_DATA_BASE = 300,
    HREQ_DATA_DEACTIVATE_PDP_CONTEXT,
    HREQ_DATA_ACTIVATE_PDP_CONTEXT,

    HREQ_NETWORK_BASE = 400,
    HREQ_NETWORK_GET_SIGNAL_STRENGTH,
    HREQ_NETWORK_GET_CS_REG_STATUS,
    HREQ_NETWORK_GET_PS_REG_STATUS,
    HREQ_NETWORK_GET_OPERATOR_INFO,
    HREQ_NETWORK_GET_SEARCH_INFORMATION,
    HREQ_NETWORK_GET_SELECTION_MODE,
    HREQ_NETWORK_SET_SELECTION_MODE,
    HREQ_NETWORK_GET_CELL_INFORMATION_LIST,
    HREQ_NETWORK_GET_CURRENT_CELL_INFORMATION,
    HREQ_NETWORK_SET_LOCATION_UPDATE,

    HREQ_COMMON_BASE = 500,
    HREQ_MODEM_SET_RADIO_STATUS,
    HREQ_MODEM_GET_RADIO_STATUS,
    HREQ_MODEM_EXIT = 1000
} HRilRequest;
#endif // OHOS_RIL_REQUEST_H
